/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tennismembership;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanele
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        txtUsername.requestFocusInWindow();
    }
    static int intUserID; // A static variable to store the ID associated with
                          // the user on the database
    String strUserName, strUserPassword, strUserRank; //Declaration of string variables to
                                                      //user details that are fetched from the database
    static String strUserIdendifier; //Declaration of a static string variable to store 
                                     //identfication of the user - member or consultant
    
    clsConnectToDatabase clsConnect = new clsConnectToDatabase(); /**A declaration of an instance of 
                                                                   * class clsConnectToDatabase. The
                                                                   * instance connects to the database
                                                                   */
    
    /**A method that returns a query that gets details of a member 
     * from the member table in the database
     */
    private String mMemberValidationQuery()
    {
        return "SELECT MemberID, Name, Password, Membership FROM tblMembers"
                + " WHERE Name ='"+txtUsername.getText()+"'AND password ='"+txtPassword.getText()+"'";
    }
    
    /**A method that returns a query that gets details of a consultant 
     * from the consultant table in the database
     */
    private String mConsultantValidationQuery()
    {
        return "SELECT ConsultantID, Name, Password, Rank FROM tblConsultants"
                + " WHERE Name ='"+txtUsername.getText()+"'AND Password ='"+txtPassword.getText()+"'";
    }
    /** A method that fetches details from the database.
     * From which table depends on the query passed as a parameter
     * @param strQuery 
     */
    private void mFetchMemberDetails(String strQuery)
    {
        Statement stStatement = null;
        ResultSet rs;
        clsConnect.mConnectToDatabaseTennisClub();
        try
        {
            stStatement = clsConnect.mConnectToDatabaseTennisClub().prepareStatement(strQuery);
            stStatement.execute(strQuery);
            rs = stStatement.getResultSet();
            while(rs.next())
            {
                intUserID = rs.getInt(1);
                strUserName = rs.getString(2);
                strUserPassword = rs.getString(3);
                strUserRank = rs.getString(4);
            }
            stStatement.close();
            rs.close();
        }
        catch(SQLException eX)
        {
            JOptionPane.showMessageDialog(null, "The application has run to a technical error\n"+eX);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dskLogin = new javax.swing.JDesktopPane();
        lblHeading = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnSubscribe = new javax.swing.JButton();
        lblLoginAs = new javax.swing.JLabel();
        cboUserStatus = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JPasswordField();
        lblLogo = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));

        dskLogin.setBackground(new java.awt.Color(153, 255, 255));

        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading.setText("Tennis Club");

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsername.setText("Username");

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPassword.setText("Password");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnSubscribe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSubscribe.setText("Subscribe");
        btnSubscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubscribeActionPerformed(evt);
            }
        });

        lblLoginAs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLoginAs.setText("Login As");

        cboUserStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner Membership", "Junior Membership", "Advanced Membership", "Professional Membership", "Junior Consultant", "Senior Consultant" }));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tennismembership/logo.png"))); // NOI18N

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        dskLogin.setLayer(lblHeading, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLogin.setLayer(lblUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLogin.setLayer(lblPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLogin.setLayer(txtUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLogin.setLayer(btnLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLogin.setLayer(btnSubscribe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLogin.setLayer(lblLoginAs, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLogin.setLayer(cboUserStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLogin.setLayer(txtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLogin.setLayer(lblLogo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dskLogin.setLayer(btnExit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dskLoginLayout = new javax.swing.GroupLayout(dskLogin);
        dskLogin.setLayout(dskLoginLayout);
        dskLoginLayout.setHorizontalGroup(
            dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskLoginLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskLoginLayout.createSequentialGroup()
                        .addGroup(dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSubscribe, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLoginAs, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblLogo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeading)
                            .addGroup(dskLoginLayout.createSequentialGroup()
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskLoginLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cboUserStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        dskLoginLayout.setVerticalGroup(
            dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dskLoginLayout.createSequentialGroup()
                .addGroup(dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dskLoginLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dskLoginLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblHeading)))
                .addGap(18, 18, 18)
                .addGroup(dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginAs)
                    .addComponent(cboUserStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dskLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubscribe)
                    .addComponent(btnLogin)
                    .addComponent(btnExit))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskLogin, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskLogin)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubscribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubscribeActionPerformed
        /** An instantiation of an instance of class frmSubscribe
         * The instance is set a title and shown when the
         * subscribe button is clicked
         * The login form is hidden
         */
        frmSubscribe frmSub = new frmSubscribe();
        frmSub.setTitle("Membership Subscription");
        frmSub.setLocation(500, 150);
        frmSub.show();
        this.hide();
    }//GEN-LAST:event_btnSubscribeActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        /** An instance of frmMainWindow is instantiated
         * User details passed to the login form input controls are checked
         * if they are equal to the given strings below.
         * If the are equal, the user is granted Senior Consultant rights.
         * The string variable strUserIdentifier is given a value, the instance
         * given a title and shown
         * If the input values are not equal the given strings, the input values
         * are checked against the ones fetched from the database. If they are equal 
         * the user is granted rights then access to the application or an appropriate 
         * error is shown         *
         */
        frmMainWindow frmMain = new frmMainWindow();
        if(txtUsername.getText().toLowerCase().equals("sanele") && txtPassword.getText().toLowerCase().equals("56001174")
                && cboUserStatus.getSelectedItem().toString().toLowerCase().equals("senior consultant"))
        {
            frmMainWindow.strUserStatus = "SENIOR CONSULTANT";
            frmMain.mSetStatusRights();
            strUserIdendifier = "Consultant";
            frmMain.setTitle("Tennis Club");
            frmMain.setVisible(true);
            this.setVisible(false);
            frmMain.setExtendedState(MAXIMIZED_BOTH);
        }
        else
        {
            try
            {    
                if(cboUserStatus.getSelectedItem().toString().endsWith("Consultant"))
                {
                    mFetchMemberDetails(mConsultantValidationQuery());
                }
                else
                {
                    mFetchMemberDetails(mMemberValidationQuery());
                }
                if(strUserRank.endsWith("Membership"))
                {
                    strUserIdendifier = "Member";
                }
                else if(strUserRank.endsWith("Consultant"))
                {
                    strUserIdendifier = "Consultant";
                }
                if(strUserName.toUpperCase().equals(txtUsername.getText().toUpperCase()) &&
                        strUserPassword.toUpperCase().equals(txtPassword.getText().toUpperCase())
                        && strUserRank.toUpperCase().equals(cboUserStatus.getSelectedItem().toString().toUpperCase()))
                    {
                    frmMainWindow.strUserStatus = cboUserStatus.getSelectedItem().toString().toUpperCase();
                    frmMain.mSetStatusRights();
                    frmMain.setTitle("Tennis Club");
                    frmMain.setVisible(true);
                    this.setVisible(false);
                    frmMain.setExtendedState(MAXIMIZED_BOTH);
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "ACCESS DENIED!! Incorrect credentials.");
                }
            }
            catch(Exception eX)
            {
                JOptionPane.showMessageDialog(null, "ACCESS DENIED!! Check Username, Password, Login as membership."
                        + "\nOr if you have subscribed your membership has not been approved yet!");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); //This line of code exits the application.
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSubscribe;
    private javax.swing.JComboBox<String> cboUserStatus;
    private javax.swing.JDesktopPane dskLogin;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLoginAs;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
